##### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [2]:
#### Answer :
import numpy as np
list_ = ['1' ,'2' , '3' , '4' , '5']
array_list = np.array(object = list_)

In [6]:
print(type(list_))
print(type(array_list))
 # we observed that there is a difference in the data type having list & array type.

<class 'list'>
<class 'numpy.ndarray'>


##### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.


In [33]:
#### Answer :

print("list_ type is:\n")
for i in array_list:
    print(type(i))


print("\narray_list type is:\n")

for i in list_:
    print(type(i))


list_ type is:

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>

array_list type is:

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


#### Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int) Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list. Consider the below code to answer further questions:

In [39]:
#### Answer:
arra_list = np.array(object = list_, dtype = int)

In [40]:
arra_list 

array([1, 2, 3, 4, 5])

In [42]:
print(type(list_))
print(type(arra_list))
 # we observed that there is a difference in the data type having list & array type.

<class 'list'>
<class 'numpy.ndarray'>


In [45]:
print("list_ type is:\n")
for i in arra_list:
    print(type(i))


print("\n arra_list type is:\n")

for i in list_:
    print(type(i))
# there is a difference in data type int and str 

list_ type is:

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>

 arra_list type is:

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


#### Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [47]:
#### Answer :

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [48]:
type(num_array)

numpy.ndarray

In [50]:
num_array.shape

(2, 3)

In [51]:
num_array.size

6

#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [54]:
#### Answer:
arr1 = np.random.randint(1,3 , (3,3))

In [55]:
arr1

array([[2, 2, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [56]:
arr1.shape

(3, 3)

In [57]:
arr1.size


9

In [ ]:
##### Q6. Create an identity matrix of shape (5,5) using numpy functions? [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [59]:
#### Answer:
np.diag(np.array([1,2,3,4,5]))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])