In [1]:
import numpy as np

In [2]:
#Numpy - Array Manipulation.

In [3]:
arr = np.random.randint(1,10 , (4,4))


In [4]:
arr

array([[9, 2, 4, 9],
       [4, 6, 9, 8],
       [5, 4, 5, 4],
       [3, 8, 7, 7]])

In [5]:
arr.reshape(8,2)

array([[9, 2],
       [4, 9],
       [4, 6],
       [9, 8],
       [5, 4],
       [5, 4],
       [3, 8],
       [7, 7]])

In [6]:
arr

array([[9, 2, 4, 9],
       [4, 6, 9, 8],
       [5, 4, 5, 4],
       [3, 8, 7, 7]])

In [7]:
arr.T

array([[9, 4, 5, 3],
       [2, 6, 4, 8],
       [4, 9, 5, 7],
       [9, 8, 4, 7]])

In [8]:
arr.flatten()

array([9, 2, 4, 9, 4, 6, 9, 8, 5, 4, 5, 4, 3, 8, 7, 7])

In [9]:
arr

array([[9, 2, 4, 9],
       [4, 6, 9, 8],
       [5, 4, 5, 4],
       [3, 8, 7, 7]])

In [10]:
np.expand_dims(arr,axis=1)

array([[[9, 2, 4, 9]],

       [[4, 6, 9, 8]],

       [[5, 4, 5, 4]],

       [[3, 8, 7, 7]]])

In [11]:
data = np.array([[1] , [2] , [3]])

In [12]:
np.squeeze(data)

array([1, 2, 3])

In [13]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [14]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [15]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [16]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [17]:
#Numpy - Binary Operators.

In [18]:
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))

In [19]:
arr1

array([[1, 3, 6, 2],
       [4, 8, 3, 6],
       [8, 4, 1, 6]])

In [20]:
arr2

array([[2, 3, 9, 7],
       [4, 3, 9, 4],
       [9, 8, 6, 8]])

In [21]:
arr1+arr2


array([[ 3,  6, 15,  9],
       [ 8, 11, 12, 10],
       [17, 12,  7, 14]])

In [22]:
arr1*arr2

array([[ 2,  9, 54, 14],
       [16, 24, 27, 24],
       [72, 32,  6, 48]])

In [23]:
arr1/arr2

array([[0.5       , 1.        , 0.66666667, 0.28571429],
       [1.        , 2.66666667, 0.33333333, 1.5       ],
       [0.88888889, 0.5       , 0.16666667, 0.75      ]])

In [24]:
arr1-arr2

array([[-1,  0, -3, -5],
       [ 0,  5, -6,  2],
       [-1, -4, -5, -2]])

In [26]:
#power
arr1**arr2


array([[        1,        27,  10077696,       128],
       [      256,       512,     19683,      1296],
       [134217728,     65536,         1,   1679616]])

In [27]:
~arr1

array([[-2, -4, -7, -3],
       [-5, -9, -4, -7],
       [-9, -5, -2, -7]])

In [28]:
arr1>arr2

array([[False, False, False, False],
       [False,  True, False,  True],
       [False, False, False, False]])

In [29]:
#Numpy - String Functions.

In [30]:
arr = np.array(["abhi" , "raj"])

In [31]:
arr

array(['abhi', 'raj'], dtype='<U4')

In [32]:
np.char.upper(arr)

array(['ABHI', 'RAJ'], dtype='<U4')

In [33]:
np.char.capitalize(arr)

array(['Abhi', 'Raj'], dtype='<U4')

In [34]:
np.char.title(arr)

array(['Abhi', 'Raj'], dtype='<U4')

In [ ]:
#Numpy - Mathematical Functions.

In [35]:
arr1

array([[1, 3, 6, 2],
       [4, 8, 3, 6],
       [8, 4, 1, 6]])

In [36]:
np.sin(arr1)

array([[ 0.84147098,  0.14112001, -0.2794155 ,  0.90929743],
       [-0.7568025 ,  0.98935825,  0.14112001, -0.2794155 ],
       [ 0.98935825, -0.7568025 ,  0.84147098, -0.2794155 ]])

In [37]:
np.cos(arr1)


array([[ 0.54030231, -0.9899925 ,  0.96017029, -0.41614684],
       [-0.65364362, -0.14550003, -0.9899925 ,  0.96017029],
       [-0.14550003, -0.65364362,  0.54030231,  0.96017029]])

In [38]:
np.tan(arr1)

array([[ 1.55740772, -0.14254654, -0.29100619, -2.18503986],
       [ 1.15782128, -6.79971146, -0.14254654, -0.29100619],
       [-6.79971146,  1.15782128,  1.55740772, -0.29100619]])

In [39]:
np.log10(arr1)

array([[0.        , 0.47712125, 0.77815125, 0.30103   ],
       [0.60205999, 0.90308999, 0.47712125, 0.77815125],
       [0.90308999, 0.60205999, 0.        , 0.77815125]])

In [40]:
np.exp(arr1)

array([[2.71828183e+00, 2.00855369e+01, 4.03428793e+02, 7.38905610e+00],
       [5.45981500e+01, 2.98095799e+03, 2.00855369e+01, 4.03428793e+02],
       [2.98095799e+03, 5.45981500e+01, 2.71828183e+00, 4.03428793e+02]])

In [41]:
np.power(arr1,2)

array([[ 1,  9, 36,  4],
       [16, 64,  9, 36],
       [64, 16,  1, 36]], dtype=int32)

In [42]:
np.mean(arr1
       )

4.333333333333333

In [43]:
np.median(arr1)

4.0

In [44]:
np.std(arr1)

2.3570226039551585

In [45]:

np.var(arr1)

5.555555555555556

In [46]:

np.min(arr1)

1

In [47]:
np.max(arr1)

8

In [48]:
#Numpy - Arithmetic Operations.

In [49]:
arr1

array([[1, 3, 6, 2],
       [4, 8, 3, 6],
       [8, 4, 1, 6]])

In [50]:
arr2

array([[2, 3, 9, 7],
       [4, 3, 9, 4],
       [9, 8, 6, 8]])

In [51]:
arr1-arr2

array([[-1,  0, -3, -5],
       [ 0,  5, -6,  2],
       [-1, -4, -5, -2]])

In [52]:
np.subtract(arr1,arr2)

array([[-1,  0, -3, -5],
       [ 0,  5, -6,  2],
       [-1, -4, -5, -2]])

In [53]:
np.multiply(arr1,arr2)

array([[ 2,  9, 54, 14],
       [16, 24, 27, 24],
       [72, 32,  6, 48]])

In [54]:
np.mod(arr1,arr2)

array([[1, 0, 6, 2],
       [0, 2, 3, 2],
       [8, 4, 1, 6]])

In [55]:
np.power(arr1,arr2)

array([[        1,        27,  10077696,       128],
       [      256,       512,     19683,      1296],
       [134217728,     65536,         1,   1679616]])

In [56]:
np.sqrt(arr1)

array([[1.        , 1.73205081, 2.44948974, 1.41421356],
       [2.        , 2.82842712, 1.73205081, 2.44948974],
       [2.82842712, 2.        , 1.        , 2.44948974]])

In [57]:
#Numpy - Statistical Functions.

In [58]:
arr

array(['abhi', 'raj'], dtype='<U4')

In [59]:
np.mean(arr1)

4.333333333333333

In [60]:
np.std(arr1)

2.3570226039551585

In [61]:
np.median(arr1)

4.0