In [1]:
##Sort, Search & Counting Functions.

In [2]:
import numpy as np

In [3]:
arr = np.array([4,2,8,5,3,9,12,56])

In [4]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [5]:
np.sort(arr)

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [6]:
np.searchsorted(arr,6)

5

In [7]:
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])

In [ ]:
np.count_nonzero(arr1)

In [8]:
np.count_nonzero(arr1)

6

In [9]:
np.where(arr1 > 0 )

(array([1, 2, 3, 4, 5, 9], dtype=int64),)

In [10]:
np.extract(arr1 >2,arr1)

array([324, 645,  65,   6,   6, 234])

In [11]:
#Numpy - Byte Swapping.

In [12]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [13]:
arr.byteswap(True)

array([ 67108864,  33554432, 134217728,  83886080,  50331648, 150994944,
       201326592, 939524096])

In [14]:
arr

array([ 67108864,  33554432, 134217728,  83886080,  50331648, 150994944,
       201326592, 939524096])

In [15]:
arr

array([ 67108864,  33554432, 134217728,  83886080,  50331648, 150994944,
       201326592, 939524096])

In [16]:
#Numpy - Copies &Views.

In [18]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [19]:
a = np.copy(arr1)

In [ ]:
b = arr1.view()

In [20]:
b = arr1

In [21]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [22]:
b[0] = 234

In [23]:
b

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [24]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [25]:
#Numpy - Matrix Library.

In [26]:
import numpy.matlib as nm


In [27]:
nm.zeros(5)


matrix([[0., 0., 0., 0., 0.]])

In [28]:
nm.ones((3,4))


matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [30]:
#Numpy - Linear Algebra

In [39]:
arr1 = np.random.randint([[2,3] , [4,5]])

In [40]:
arr2 = np.random.randint([[5,3] , [2,5]])


In [41]:
arr1

array([[1, 0],
       [1, 4]])

In [42]:
arr2

array([[3, 2],
       [1, 4]])

In [43]:
np.dot(arr1,arr2)

array([[ 3,  2],
       [ 7, 18]])

In [44]:
arr1@arr2

array([[ 3,  2],
       [ 7, 18]])